# Setup
# title: C ve Sistem Programcıları Derneği
# subtitle: CSD
# tagline: CSD
# description:  'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
# url:                 http://lanyon.getpoole.com
# baseurl:             ''
# paginate:            5

permalink: pretty
email: your-email@example.com
description: >- 
  C ve Sistem Programcıları Derneği, 
  çalışmalarını C/C++ programlama dilleri ile yürüten 
  ve deneyimlerini sistem programlama alanı ile ilişkilendiren 
  uzmanların oluşturduğu bir dernektir.
baseurl: "" 
# the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
paginate: 5

theme: minima

collections:
  courses:
   output: true



plugins:
  - jekyll-feed
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
